feat: add rundeck 3.x installation
chaordic/ansible-role-rundeck pull request #12
Opened 2019-04-02 21:21 UTC by weslleycamilo

2019-05-09 13:18 UTC, weslleycamilo commented on tasks/projects.yml
> +    dest: "/etc/rundeck/{{ item }}.properties"
Create new folder for its properties to clean up the `/etc/rundec/` folder

2019-10-14 20:06 UTC, mtulio requested changes
@weslleycamilo all of this changes was yours or do you merge changes from upstream role and yours?
Is it possible to separate each one to understand what was your changes (and review it), from community repo.

When we do that, we will understand what and how we can contribute back to the upstream.

2019-12-09 13:29 UTC, weslleycamilo commented
It was all mine.  There are some changes which are in our role which we didn't push back to the community so I believe we can merge it and push everything we've done until now to the community so we don't have to wait his approval to get our code updated right ?

2019-12-09 13:56 UTC, cassiomcouto approved these changes

2019-12-09 17:06 UTC, raphapr requested changes

2019-12-09 17:06 UTC, raphapr commented on templates/nginx/rundeck.conf.j2
> +#server {
what about remove these commented lines? once there is no use for this

2019-12-09 17:06 UTC, raphapr commented on templates/rundeckd.j2
> +RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -Xmx{{max_heap}}m -Xms256m -XX:MaxMetaspaceSize=256m -server}"
where `max_heap` is defined? what about parametrize jvm settings as default vars instead? it gives more versatility for the role

please, see my sugestions and let me know what you think about.

2019-12-09 17:06 UTC, raphapr commented on templates/rundeckd.j2
> +RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -Xmx{{max_heap}}m -Xms256m -XX:MaxMetaspaceSize=256m -server}"
```suggestion
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- {{ rundeck_jvm_settings }}"
```

2019-12-09 17:06 UTC, raphapr commented on templates/rundeckd.j2
> +RDECK_JVM_OPTS="-Drundeck.jaaslogin=true \
```suggestion
RDECK_JVM_OPTS="{{ rundeck_jvm_opts }}"
```

2019-12-09 17:06 UTC, raphapr commented on templates/rundeckd.j2
> +       -Djava.security.auth.login.config=/etc/rundeck/jaas-multiauth.conf \
```suggestion
```

2019-12-09 17:06 UTC, raphapr commented on templates/rundeckd.j2
> +       -Dloginmodule.name=multiauth"
```suggestion
```

2019-12-09 17:06 UTC, raphapr commented on defaults/main.yml
```suggestion
rundeck_jvm_settings: "-Xmx256m -Xms256m -XX:MaxMetaspaceSize=256m -server"
rundeck_jvm_opts: "-Drundeck.jaaslogin=true -Djava.security.auth.login.config=/etc/rundeck/jaas-multiauth.conf -Dloginmodule.name=multiauth"
```

2019-12-09 17:10 UTC, weslleycamilo commented on templates/rundeckd.j2
> +RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -Xmx{{max_heap}}m -Xms256m -XX:MaxMetaspaceSize=256m -server}"
great @raphapr

2019-12-09 17:12 UTC, weslleycamilo commented on templates/nginx/rundeck.conf.j2
> +#server {
I'm going to still use it as the old rundeck but just to not use the certs I commented it at the time.

2019-12-09 17:17 UTC, raphapr approved these changes

2019-12-09 17:18 UTC, raphapr approved these changes

2019-12-09 18:38 UTC, raphapr commented on defaults/main.yml
>  rundeck_tmpdir: /tmp/rundeck
```suggestion
rundeck_tmpdir: /tmp/rundeck

# JVM parameters
```

2019-12-09 18:38 UTC, raphapr commented on defaults/main.yml
> +rundeck_jvm_opts: "-Drundeck.jaaslogin=true -Djava.security.auth.login.config=/etc/rundeck/jaas-multiauth.conf -Dloginmodule.name=multiauth"
```suggestion
rundeck_jvm_opts: "-Drundeck.jaaslogin=true -Djava.security.auth.login.config=/etc/rundeck/jaas-multiauth.conf -Dloginmodule.name=multiauth"

```

2019-12-10 17:25 UTC, merged