LDAP module support
chaordic/ansible-role-rundeck pull request #5
Opened 2017-05-26 17:40 UTC by raphapr

2017-06-02 22:42 UTC, mtulio requested changes

2017-06-02 22:42 UTC, mtulio commented on templates/rundeck-config.groovy.j2
> +rundeck.executionMode = "passive"
Should not set default as 'passive' mode.

2017-06-02 22:42 UTC, mtulio commented on templates/profile.j2
> +       -Dloginmodule.name={{ 'ldap' if rd_login_module == 'ldap' else 'RDpropertyfilelogin' }} \
This conditional check could be improved. http://jinja.pocoo.org/docs/2.9/templates/#if

2017-06-02 23:11 UTC, raphapr commented on templates/profile.j2
> +       -Dloginmodule.name={{ 'ldap' if rd_login_module == 'ldap' else 'RDpropertyfilelogin' }} \
done

2017-06-05 20:54 UTC, mtulio approved these changes

2017-06-07 22:36 UTC, mtulio commented
You could sqash and merge this PR. :)

2017-06-08 16:50 UTC, merged